config/routes.rb
Rails.application.routes.draw do
  post 'agreement_letters/create'
  get 'agreement_letters/show'

  resources :requests
  resources :application_letters, path: 'applications' do
    resources :application_notes,
      only: :create
  end
  resources :events do
    resources :agreement_letters, only: [:create], shallow: true
    get 'badges'
    post 'badges' => 'events#print_badges', as: :print_badges
  end
  resources :profiles
  devise_for :users

  root 'application#index'

  get 'events/:id/participants' => 'events#participants'
  get 'events/:id/send-acceptance-emails' => 'events#send_acceptance_emails', as: :event_send_acceptance_emails
  get 'events/:id/send-rejection-emails' => 'events#send_rejection_emails', as: :event_send_rejection_emails

  post 'send_email' => 'emails#send_email'

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Profile < ActiveRecord::Base
  POSSIBLE_GENDERS = ['male', 'female', 'other']
  
  belongs_to :user

  validates :user, presence: true
  validates_presence_of :first_name, :last_name, :gender, :birth_date, :school, :street_name, :zip_code, :city, :state, :country
  validate :birthdate_not_in_future
  validates_inclusion_of :gender, in: POSSIBLE_GENDERS


  # Returns true if the user is 18 years old or older
  #
  # @param none
  # @return [Boolean] whether the user is an adult
  def adult?()
    self.birth_date >= 18.years.ago
  end

  # Returns the age of the user based on the current date
  #
  # @param none
  # @return [Int] for age as number of years
  def age
    now = Time.now.utc.to_date
    current_time_is_before_birthday = now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)
    return now.year - birth_date.year - (current_time_is_before_birthday ? 0 : 1)
  end

  # Returns the Full Name of the user
  #
  # @param none
  # @return [String] of name
  def name
    first_name + " " +  last_name
  end

  # Returns the address of the user
  # in Format: Street, Zip-Code City, State, Country
  #
  # @param none
  # @return [String] of address
  def address
    street_name + ", " + zip_code + " " +  city + ", " + state + ", " + country
  end

  private
  def birthdate_not_in_future
    if birth_date.present? and birth_date > Date.current
      errors.add(:birth_date, I18n.t('profiles.validation.birthday_in_future'))
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource

  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    flash.keep(:event_id)
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    if @profile.save
      if flash[:event_id]
        redirect_to new_application_letter_path(:event_id => flash[:event_id])
      else
        redirect_to @profile
      end
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :gender, :birth_date, :school, :street_name, :zip_code, :city, :state, :country, :graduates_school_in)
    end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :class => "form-horizontal profile" } do |f| %>

  <%= render partial: "shared/error_message", locals: {entity: @profile} %>

  <%# Create an input field for each of the mandatory attributes%>
  <% [:first_name, :last_name, :gender, :birth_date, :school, :street_name, :zip_code, :city, :state, :country].each do |attr_name| %>
    <div class="form-group">
      <%= f.label attr_name, :class => 'control-label col-lg-2 required'%>
      <div class="col-lg-10">
        <% if attr_name == :birth_date %>
          <%= f.text_field attr_name, :class => 'form-control', :"data-enable-datepicker" => "true", value: (I18n.l @profile.birth_date if @profile.birth_date) %>
        <% elsif attr_name == :gender %>
          <%= f.select :gender, options_for_select(Profile::POSSIBLE_GENDERS.collect {|d| [I18n.t("profiles.genders.#{d}"), d]}, @profile.gender), {}, {class: 'form-control'} %>
        <% else %>
          <%= f.text_field attr_name, :class => 'form-control' %>
        <% end %>
        <%=f.error_span(attr_name) %>
      </div>
    </div>
  <% end %>

  <%# Create a special drop-down for likely graduation year%>
  <div class="form-group">
    <%= f.label :graduates_school_in, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:graduates_school_in, Array(Time.now.year..Time.now.year+15).unshift(t '.already_graduated').unshift(""), :to_s, :to_s, {}, {:class=>'form-control'}) %>
      <%=f.error_span(:graduates_school_in) %>
    </div>
  </div>

  <div class="text-right col-lg-12" >
    <label class="required"> </label>
    <%= t("errors.messages.required") %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                profiles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/profiles/_upload_form.html.erb
<%= form_tag(event_agreement_letters_path(event_id), multipart: true) do %>

  <% if agreement_letter.nil? %>
    <% upload_message = t("agreement_letters.upload") %>
  <% else %>
    <% upload_message = t('.update', default: t("agreement_letters.update")) %>
    <% already_uploaded_msg = t("agreement_letters.already_uploaded", timestamp: l(agreement_letter.updated_at)) %>
  <% end %>

  <span class="help-block bg-success"><%= already_uploaded_msg %></span>
  <%= file_field_tag "letter_upload",
    class: "btn btn-default btn-file",
    style: 'display:inline',
    id: "letter_upload_#{event_id}",
    accept: "application/pdf" %>
  <%= submit_tag upload_message,
    class: 'btn btn-default',
    id: "upload_btn_#{event_id}" %>
<% end %>

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(count: 2).titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <% if can? :destroy, profile %>
        <tr>
          <td><%= link_to profile.id, profile_path(profile) %></td>
          <td><%= profile.user_id %></td>
          <td><%= profile.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_profile_path(profile), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        profile_path(profile),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_profile_path,
            :class => 'btn btn-primary' %>

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/show.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <% [:first_name, :last_name, :gender, :birth_date, :school, :street_name, :zip_code, :city, :state, :country, :graduates_school_in].each do |attr_name| %>
    <dt><strong><%= model_class.human_attribute_name(attr_name) %>:</strong></dt>
    <% if attr_name == :gender %>
      <dd><%= t("profiles.genders.#{@profile.public_send(attr_name)}") %></dd>
    <% else %>
      <dd><%= @profile.public_send(attr_name) %></dd>
    <% end %>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              profiles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_profile_path(@profile), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              profile_path(@profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<h3>Events</h3>
<table id='events_table', class='table table-bordered table-hover'>
  <thead>
    <tr>
      <th>id</th>
      <th><%= t('agreement_letters.agreement_letter') %></th>
    </tr>
  </thead>
  <tbody>
    <% @profile.user.events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td>
          <% if @profile.adult? %>
            <%= render('upload_form',
              event_id: event.id,
              agreement_letter: event.agreement_letter_for(@profile.user)) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>