config/routes.rb
Rails.application.routes.draw do
  post 'agreement_letters/create'
  get 'agreement_letters/show'

  resources :requests
  resources :application_letters, path: 'applications' do
    resources :application_notes,
      only: :create
  end
  resources :events do
    resources :agreement_letters, only: [:create], shallow: true
    get 'badges'
    post 'badges' => 'events#print_badges', as: :print_badges
  end
  resources :profiles
  devise_for :users

  root 'application#index'

  get 'events/:id/participants' => 'events#participants'
  get 'events/:id/send-acceptance-emails' => 'events#send_acceptance_emails', as: :event_send_acceptance_emails
  get 'events/:id/send-rejection-emails' => 'events#send_rejection_emails', as: :event_send_rejection_emails

  post 'send_email' => 'emails#send_email'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :store_current_location, :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => exception.message }
    end
  end

  def index

  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :name, :password, :password_confirmation, :role)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :name, :password, :password_confirmation, :role, :current_password)
    end
  end

  private
  # override the devise helper to store the current location so we can
  # redirect to it after logging in or out. This override makes signing in
  # and signing up work automatically.
  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_items
    (menu_item t(:home, scope: 'navbar'), root_path) +
    (menu_item t(:events, scope: 'navbar'), events_path) +
    (menu_item t(:requests, scope: 'navbar'), requests_path)
  end

  def dropdown_items
    o = ''
    # everyone gets settings
    o << (menu_item t(:settings, scope: 'navbar'), edit_user_registration_path)
    # everyone gets their profile, if it exists
    if current_user.profile.present?
      o << (menu_item t(:profile, scope: 'navbar'), profile_path(current_user.profile))
    else
      o << (menu_item t(:create_profile, scope: 'navbar'), new_profile_path)
    end
    # pupils get their applications
    if current_user.role == "pupil"
      o << (menu_item t(:my_application_letters, scope: 'navbar'), application_letters_path)
    end
    # admins get user management
    if current_user.role == "admin"
      o << (menu_item t(:user_management, scope: 'navbar'), profiles_path)
    end
    # everyone gets logout
    o << (menu_item t(:logout, scope: 'navbar'), destroy_user_session_path, :method => :delete)

    o.html_safe
  end
end

app/views/applications/_form.html.erb
<%= form_for @application, :html => { :class => "form-horizontal application" } do |f| %>

  <% if @application.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :motivation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :motivation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:motivation) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :workshop_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :workshop_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:workshop_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                applications_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/applications/edit.html.erb
<%- model_class = Application -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applications/index.html.erb
<%- model_class = Application -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:motivation) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:workshop_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= link_to application.id, application_path(application) %></td>
        <td><%= application.motivation %></td>
        <td><%= application.user_id %></td>
        <td><%= application.workshop_id %></td>
        <td><%=l application.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_application_path(application), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      application_path(application),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_application_path,
            :class => 'btn btn-primary' %>

app/views/applications/new.html.erb
<%- model_class = Application -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applications/show.html.erb
<%- model_class = Application -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:motivation) %>:</strong></dt>
  <dd><%= @application.motivation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @application.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:workshop_id) %>:</strong></dt>
  <dd><%= @application.workshop_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              applications_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_application_path(@application), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              application_path(@application),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>