config/routes.rb
Rails.application.routes.draw do
  post 'agreement_letters/create'
  get 'agreement_letters/show'

  resources :requests
  resources :application_letters, path: 'applications' do
    resources :application_notes,
      only: :create
  end
  resources :events do
    resources :agreement_letters, only: [:create], shallow: true
    get 'badges'
    post 'badges' => 'events#print_badges', as: :print_badges
  end
  resources :profiles
  devise_for :users

  root 'application#index'

  get 'events/:id/participants' => 'events#participants'
  get 'events/:id/send-acceptance-emails' => 'events#send_acceptance_emails', as: :event_send_acceptance_emails
  get 'events/:id/send-rejection-emails' => 'events#send_rejection_emails', as: :event_send_rejection_emails

  post 'send_email' => 'emails#send_email'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id               :integer          not null, primary key
#  name             :string
#  description      :string
#  max_participants :integer
#  date_ranges      :Collection
#  active           :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  application_status_locked  :boolean
#

class Event < ActiveRecord::Base
  UNREASONABLY_LONG_DATE_SPAN = 300

  has_many :application_letters
  has_many :agreement_letters
  has_many :date_ranges
  accepts_nested_attributes_for :date_ranges

  # Returns all participants for this event in following order:
  # 1. All participants that have to submit an letter of agreement but did not yet do so, ordered by name.
  # 2. All participants that have to submit an letter of agreement and did do so, ordered by name.
  # 3. All participants that do not have to submit an letter of agreement, ordered by name.
  #
  # @param none
  # @return [Array<User>] the event's participants in that order.
  def participants_by_agreement_letter
    @participants = self.participants
	@participants.sort { |x, y| self.compare_participants_by_agreement(x,y) }
  end

  validates :max_participants, numericality: { only_integer: true, greater_than: 0 }
  validate :has_date_ranges
  validates_presence_of :application_deadline
  validate :application_deadline_before_start_of_event


  # @return the minimum start_date over all date ranges
  def start_date
    (date_ranges.min { |a,b| a.start_date <=> b.start_date }).start_date
  end

  # @return the minimum end_date over all date ranges
  def end_date
    (date_ranges.max { |a,b| a.end_date <=> b.end_date }).end_date
  end

  # @return whether this event appears unreasonably long as defined by
  #         the corresponding constant
  def unreasonably_long
    end_date - start_date > Rails.configuration.unreasonably_long_event_time_span
  end

  # validation function on whether we have at least one date range
  def has_date_ranges
    errors.add(:date_ranges, I18n.t('date_range.errors.no_timespan')) if date_ranges.blank?
  end

  #validate that application deadline is before the start of the event
  def application_deadline_before_start_of_event
    errors.add(:application_deadline, I18n.t('events.errors.application_deadline_before_start_of_event')) if application_deadline.present? && !date_ranges.blank? && application_deadline > start_date
  end

  # Returns the participants whose application for this Event has been accepted
  #
  # @param none
  # @return [Array<User>] the event's participants
  def participants
    accepted_applications = application_letters.where(status: ApplicationLetter.statuses[:accepted])
    accepted_applications.collect { |a| a.user }
  end

  # Returns the agreement letter a user submitted for this event
  #
  # @param user [User] the user whose agreement letter we want
  # @return [AgreementLetter, nil] the user's agreement letter or nil
  def agreement_letter_for(user)
    self.agreement_letters.where(user: user).take
  end

  enum kind: [ :workshop, :camp ]

  # Returns whether all application_letters are classified or not
  #
  # @param none
  # @return [Boolean] if status of all application_letters is not pending
  def applications_classified?
    application_letters.all? { |application_letter| application_letter.status != 'pending' }
  end

  # Returns a string of all email addresses of accepted applications
  #
  # @param none
  # @return [String] Concatenation of all email addresses of accepted applications, seperated by ','
  def email_adresses_of_accepted_applicants
    accepted_applications = application_letters.where(status: ApplicationLetter.statuses[:accepted])
    accepted_applications.map{ |application_letter| application_letter.user.email }.join(',')
  end

  # Returns a string of all email addresses of rejected applications
  #
  # @param none
  # @return [String] Concatenation of all email addresses of rejected applications, seperated by ','
  def email_adresses_of_rejected_applicants
    rejected_applications = application_letters.where(status: ApplicationLetter.statuses[:rejected])
    rejected_applications.map{ |applications_letter| applications_letter.user.email }.join(',')
  end

  # Returns a new acceptance email
  #
  # @param none
  # @return [Email] new acceptance email
  def generate_acceptances_email
    email = Email.new
    email.hide_recipients = false
    email.recipients = email_adresses_of_accepted_applicants
    email.reply_to = 'workshop.portal@hpi.de'
    email.subject = ''
    email.content = ''
    return email
  end

  # Returns a new rejection email
  #
  # @param none
  # @return [Email] new rejection email
  def generate_rejections_email
    email = Email.new
    email.hide_recipients = false
    email.recipients = email_adresses_of_rejected_applicants
    email.reply_to = 'workshop.portal@hpi.de'
    email.subject = ''
    email.content = ''
    return email
  end

  # Returns the number of free places of the event, this value may be negative
  #
  # @param none
  # @return [Int] for number of free places available
  def compute_free_places
    max_participants - compute_occupied_places
  end

  # Returns the number of already occupied places of the event
  #
  # @param none
  # @return [Int] for number of occupied places
  def compute_occupied_places
    application_letters.where(status: ApplicationLetter.statuses[:accepted]).count
  end

  # Make sure any assignment coming from the controller
  # replaces all date ranges instead of adding new ones
  def date_ranges_attributes=(*args)
    self.date_ranges.clear
    super(*args)
  end

  # Make sure we add errors from our date_range children
  # to the base event object for displaying
  validate do |event|
    event.date_ranges.each do |date_range|
      next if date_range.valid?
      date_range.errors.full_messages.each do |msg|
        errors.add :date_ranges, msg
      end
    end
  end

  scope :draft_is, ->(draft) { where("draft = ?", draft) }

  protected
  # Compares two participants to achieve following order:
  # 1. All participants that have to submit an letter of agreement but did not yet do so, ordered by name.
  # 2. All participants that have to submit an letter of agreement and did do so, ordered by name.
  # 3. All participants that do not have to submit an letter of agreement, ordered by name.
  def compare_participants_by_agreement(participant1, participant2)
    if participant1.requires_agreement_letter_for_event?(self)
      if participant2.requires_agreement_letter_for_event?(self)
        return participant1.name <=> participant2.name
      end
      return 1
    end
    if participant2.requires_agreement_letter_for_event?(self)
      return -1
    end
    if participant1.agreement_letter_for_event?(self)
      if participant2.agreement_letter_for_event?(self)
        return participant1.name <=> participant2.name
      end
      return 1
    end
    if participant2.agreement_letter_for_event?(self)
      return -1
    end
    return participant1.name <=> participant2.name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.draft_is false
  end

  # GET /events/1
  def show
    @free_places = @event.compute_free_places
    @occupied_places = @event.compute_occupied_places
    @application_letters = filter_application_letters(@event.application_letters)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    @event.draft = (params[:draft] != nil)

    if @event.save
      redirect_to @event, notice: I18n.t('.events.notices.created')
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    attrs = event_params

    @event.draft = (params[:commit] == "draft")

    if @event.update(attrs)
      redirect_to @event, notice: I18n.t('events.notices.updated')
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('events.notices.destroyed')
  end

  # GET /events/1/badges
  def badges
    @event = Event.find(params[:event_id])
    @participants = @event.participants
  end

  # POST /events/1/badges
  def print_badges
    names = badges_name_params

    # pdf document initialization
    pdf = Prawn::Document.new(:page_size => 'A4')
    pdf.stroke_color "000000"

    # divide in pieces of 10 names
    badge_pages = names.each_slice(10).to_a
    badge_pages.each_with_index do | page, index |
      create_badge_page(pdf, page, index)
    end


    send_data pdf.render, filename: "badges.pdf", type: "application/pdf", disposition: "inline"
  end

  # GET /events/1/participants
  def participants
    @event = Event.find(params[:id])
    @participants = @event.participants_by_agreement_letter
  end

  # GET /events/1/send-acceptances-email
  def send_acceptance_emails
    event = Event.find(params[:id])
    @email = event.generate_acceptances_email
    @templates = [{subject: 'Zusage 1', content: 'Lorem Ispum...'}, {subject: 'Zusage 2', content: 'Lorem Ispum...'}, {subject: 'Zusage 3', content: 'Lorem Ispum...'}]
    render :email
  end

  # GET /events/1/send-rejections-email
  def send_rejection_emails
    event = Event.find(params[:id])
    @email = event.generate_rejections_email
    @templates = [{subject: 'Absage 1', content: 'Lorem Ispum...'}, {subject: 'Absage 2', content: 'Lorem Ispum...'}, {subject: 'Absage 3', content: 'Lorem Ispum...'}]
    render :email
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :description, :max_participants, :kind, :organizer, :knowledge_level, :application_deadline, date_ranges_attributes: [:start_date, :end_date, :id])
    end

    # Generate all names to print from the query-params
    #
    # @return participant_names as array of strings
    def badges_name_params
      params.select { |key, value| key.include? "_print" }.values
    end

    # Create a name badge in a given pdf
    #
    # @param pdf, is a prawn pdf-object
    # @param name [String] is the name label of the new badge
    # @param x [Integer] is the x-coordinate of the upper left corner of the new badge
    # @param y [Integer] is the y-coordinate of the upper left corner of the new badge
    def create_badge(pdf, name, x, y)
      width = 260
      height = 150

      pdf.stroke_rectangle [x, y], width, height
      pdf.text_box name, :at => [x + width / 2 - 50 , y - 20], :width => width - 100, :height => height - 100, :overflow => :shrink_to_fit
    end

    def filter_application_letters(application_letters)
      application_letters = application_letters.to_a
      filters = (params[:filter] || {}).select { |k, v| v == '1' }.map{ |k, v| k.to_s }
      if filters.count > 0  # skip filtering if no filters have been set
        application_letters.keep_if { |l| filters.include?(l.status) }
      end
      application_letters
    end

    # Create a page with maximum 10 badges
    #
    # @param pdf, is a prawn pdf-object
    # @param names [Array of Strings] are the name which are printed to the badges
    # @param index [Number] the page number
    def create_badge_page(pdf, names, index)
      # create no pagebreak for first page
      pdf.start_new_page if index > 0

      names.each_slice(2).with_index do |(left, right), row|
        create_badge(pdf, left, 0, 750 - row * 150)
        create_badge(pdf, right, 260, 750 - row * 150) unless right.nil?
      end
    end
end

app/views/events/_applicants_overview.html.erb
<div class="container-fluid" id="applicants_overview">
  <h3><%= t '.title', title: @event.name %></h3>
  <div id="free_places"><%= t '.free_places', count: @free_places %></div>
  <div id="occupied_places"><%= t '.occupied_places', count: @occupied_places %></div>

  <table id="applicants" class="table table-striped">
    <thead>
    <tr>
      <th>
        <%= sort_caret(Profile.human_attribute_name(:name), :name) %>
      </th>
      <th>
        <%= sort_caret(Profile.human_attribute_name(:gender), :gender) %>
      </th>
      <th>
        <%= sort_caret(Profile.human_attribute_name(:age), :age) %>
      </th>
      <th>
        <%= t '.participations' %> <br>
        <%= t '.accepted_rejected' %>
      </th>
      <th>
        <button
         class="btn btn-default btn-sm pull-right has-popover"
         title="<%= t '.filter_by' %>"
         data-toggle="popover"
         data-placement="bottom"
         data-content="<%= (render :partial => 'application_letters/application_filter_popover').gsub('\n', '') %>"
         data-html="true"><%= t '.filter_by' %></button>
        <%= t '.status' %>
      </th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%
      @application_letters.sort_by! {|l| l.user.profile.send(params[:sort]) } if params[:sort]
      @application_letters.reverse! if params[:order] == 'descending'
      @application_letters.select {|l| l.user.profile }.each do | application_letter | %>
        <tr>
          <td><%= application_letter.user.profile.name %></td>
          <td><%= application_letter.user.profile.gender %></td>
          <td><%= application_letter.user.profile.age  %></td>
          <td><%= application_letter.user.accepted_applications_count(@event) %> / <%= application_letter.user.rejected_applications_count(@event) %></td>
          <td>
            <%= render :partial => 'application_letters/application_selective', locals: {application_letter: application_letter} %>
          </td>
          <td>
            <%= link_to t('.details'), application_letter_path(application_letter), :class => 'btn btn-default' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="container-fluid no-padding">
    <div class="btn-group" role="group">
      <%= link_to "Alle annehmen",
          events_path, :class => 'btn btn-default'%>

      <%= link_to "Alle drucken",
          events_path, :class => 'btn btn-default'%>
    </div>

    <% if not @event.applications_classified? %>
      <div class="btn-group pull-right tooltip-wrapper has-tooltip" role="group" data-toggle="tooltip" title="<%= t '.unclassified_applications_left'%>">
        <%= link_to t('events.badges.print_button_label'), event_badges_path(@event), :class => 'btn btn-default'%>
        <%= button_tag t('.sending_acceptances'), type: 'button', class: 'send-emails-button btn btn-default', disabled: true %>
        <%= button_tag t('.sending_rejections'), type: 'button', class: 'send-emails-button btn btn-default', disabled: true %>
      </div>
    <% elsif (@event.compute_free_places < 0) %>
      <div class="btn-group pull-right tooltip-wrapper has-tooltip" role="group" data-toggle="tooltip" title="<%= t '.maximum_number_of_participants_exeeded'%>">
        <%= link_to t('events.badges.print_button_label'), event_badges_path(@event), :class => 'btn btn-default'%>
        <%= button_tag t('.sending_acceptances'), type: 'button', class: 'send-emails-button btn btn-default', disabled: true %>
        <%= button_tag t('.sending_rejections'), type: 'button', class: 'send-emails-button btn btn-default', disabled: true %>
      </div>
    <% else %>
      <div class="btn-group pull-right" role="group">
        <%= link_to t('events.badges.print_button_label'), event_badges_path(@event), :class => 'btn btn-default'%>
        <%= link_to t('.sending_acceptances'), event_send_acceptance_emails_path, class: 'send-emails-button btn btn-default' %>
        <%= link_to t('.sending_rejections'), event_send_rejection_emails_path, class: 'send-emails-button btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>

  <%= render partial: "shared/error_message", locals: {entity: @event} %>

  <div class="form-group">
    <div class="btn-group col-lg-10 col-lg-offset-2" data-toggle="buttons">
      <% Event.kinds.keys.each do |key| %>
        <label class="btn btn-default <%= 'active' if @event.kind == key %>">
          <%= f.radio_button :kind, key %>
          <%= key.humanize %>
        </label>
      <% end %>
      <%=f.error_span(:kind) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
      <%=f.error_span(:name) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
      <%=f.error_span(:description) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :max_participants, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :max_participants, :class => 'form-control' %>
      <%=f.error_span(:max_participants) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_ranges, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10" id="event-date-pickers">
      <% def date_picker_template(start_date = Date.current, end_date = Date.current)
        start_picker = text_field_tag "event[date_ranges_attributes][][start_date]", (I18n.l start_date),
          class: 'form-control', :"data-enable-datepicker" => 'true'
        end_picker = text_field_tag "event[date_ranges_attributes][][end_date]", (I18n.l end_date),
          class: 'form-control', :"data-enable-datepicker" => 'true'

        "<div>#{start_picker} #{t 'date_range.to'} #{end_picker} "+
          "<a class=\"close\" onclick=\"javascript:removeEventDatePicker(event.target)\">&times;</a></div>"
      end %>

      <%=
        if @event.date_ranges.blank?
          date_picker_template.html_safe
        else
          @event.date_ranges
            .map { |d| date_picker_template d.start_date, d.end_date }
            .reduce(:+)
            .html_safe
        end
      %>
      <a class="btn btn-xs btn-default" href="javascript:addEventDatePicker()" id="event-add-date-picker">
        <%= t 'events.form.add_timespan' %>
      </a>
      <%=f.error_span(:date_ranges) %>
    </div>
    <script>var EVENT_DATE_PICKER_TEMPLATE = '<%= date_picker_template.gsub("\n", "").html_safe %>';</script>
  </div>
  <div class="form-group">
    <%= f.label :organizer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :organizer, :class => 'form-control', :placeholder => 'optional' %>
      <%=f.error_span(:organizer) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :knowledge_level, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :knowledge_level, :class => 'form-control', :placeholder => 'optional' %>
      <%=f.error_span(:knowledge_level) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :application_deadline, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :application_deadline, :"data-enable-datepicker" => 'true', value: ((I18n.l  @event.application_deadline) if @event.application_deadline.present?), class: "form-control" %>
      <%=f.error_span(:application_deadline) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <% if @event.draft == false %>
        <%= f.submit t('.update'), :name => 'publish', :class => 'btn btn-primary' %>
      <% else %>
        <%= f.submit t('.publish'), :name => 'publish', :class => 'btn btn-primary' %>
        <%= f.submit t('.draft'), :name => 'draft', :class => 'btn btn-default' %>
      <% end %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/events/_show_event.html.erb
<%- model_class = Event -%>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:max_participants) %>:</strong></dt>
  <dd><%= @event.max_participants %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_ranges, count: @event.date_ranges.count) %>:</strong></dt>
  <dd>
    <ul>
    <% @event.date_ranges.each do |r| %>
      <li><%= r.to_s %></li>
    <% end %>
    </ul>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:organizer) %>:</strong></dt>
  <dd><%= @event.organizer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:knowledge_level) %>:</strong></dt>
  <dd><%= @event.knowledge_level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:application_deadline) %>:</strong></dt>
  <dd> <%= I18n.l(@event.application_deadline) + ' ' + I18n.t('midnight') %></dd>
</dl>
<%= link_to t('.new', :default => t("helpers.links.apply")), new_application_letter_path(:event_id => @event.id),
                      :class => 'btn btn-info' %>

app/views/events/badges.html.erb
<h1><%= t('events.badges.title') + "'" + @event.name + "'" %></h1>
<h3><%= t('events.badges.participants') %></h3>

<%= form_for event_badges_path(@event), :html => { :class => "form-horizontal event" } do |f| %>
<table>
  <tr>
    <th><%= Profile.human_attribute_name(:name) %></th>
    <th><%= t('events.badges.printBoolean') %></th>
  </tr>

  <% @participants.each do |participant| %>
      <tr>
        <td>
          <%= participant.name %>
        </td>
        <td>
          <%= f.check_box_tag "#{participant.id}_print", participant.name%>
        </td>
      </tr>
  <% end %>
</table>


<%= f.submit t('events.badges.print'), :class => 'btn btn-primary' %>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/email.erb
<%- model_class = Event -%>
<div class="page-header">
</div>
<div>
  <div class="email-form col-md-8">
    <%= render partial: 'emails/email_form', locals: { email: @email} %>
  </div>
  <div class="email-templates col-md-4">
    <p><%= t('.templates') %></p>
    <div class="list-group">
      <% @templates.each do |template| %>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading"><%= template[:subject] %></h4>
          <p class="list-group-item-text"><%= template[:content] %></p>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:kind) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:draft) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= I18n.t "events.kinds.#{event.kind}" %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.draft %></td>
        <td>
          <%= link_to t('.edit', :default => t('helpers.links.edit')),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t('helpers.links.destroy')),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('events.confirmation_prompts.confirm_delete', :default => t("helpers.links.confirm", :default => 'Löschen kann nicht rückgängig gemacht werden!')) },
                      :class => 'btn btn-xs btn-danger' %>
					<%= link_to t('.new', :default => t('helpers.links.apply')),
                      new_application_letter_path(:event_id => event.id),
                      :class => 'btn btn-xs btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t('helpers.links.new')),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Neues %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/participants.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %> (<%= @event.kind.humanize %>)</h1>
</div>
<% if can? :view_participants, Event %>
  <%= render :partial => 'show_event' %>
  
  <h1><%= t '.participants' %></h1>
  <table class="table table-striped">
    <tr>
      <th><%= t 'activerecord.attributes.profile.name' %></th>
      <th><%= t 'activerecord.attributes.profile.email' %></th>
  	  <th><%= t 'agreement_letters.agreement_letter' %></th>
    </tr>  
  
    <% @participants.each do |participant| %>
    <tr>
      
      <td>
      <%= participant.name %>
      </td>
      <td>
      <%= participant.email %>
      </td>
      <td>
        <% if participant.requires_agreement_letter_for_event?(@event) %>
          <span class="text-muted"> <%= t '.unnecessary' %> </span>
        <% elsif participant.agreement_letter_for_event?(@event) %>
          <span class="text-success" title="<%= participant.agreement_letter_for_event(@event).updated_at %>"> <%= t '.available' %> </span>
        <% else %>
          <span class="text-danger"><%= t '.unavailable' %></span>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
  
  
  <%= link_to t('.back', :default => t('helpers.links.back')),
              event_path(@event), :class => 'btn btn-default'  %>
<% end %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %> (<%= @event.kind.humanize %>)</h1>
</div>

<% if @event.unreasonably_long %>
  <div class="panel panel-warning">
    <div class="panel-body">
      <%= t 'events.notices.unreasonable_timespan' %>
    </div>
  </div>
<% end %>

<%= render :partial => 'show_event' %>

<% if can? :view_applicants, Event %>
  <%= render :partial => 'applicants_overview' %>
<% end %>

<%= link_to t('.back', :default => t('helpers.links.back')),
              events_path, :class => 'btn btn-default'  %>
<% if can? :view_participants, Event %>
  <%= link_to t('events.participants.show_participants'),
              event_path(@event) + "/participants" , :class => 'btn btn-default'  %>
<% end %>